DOCKER_PREFIX=${DOCKER_PREFIX:-"quay.io/kubevirt"}
DOCKER_IMAGE=${DOCKER_IMAGE:-"builder-aie-nv"}
DOCKER_CROSS_IMAGE=${DOCKER_CROSS_IMAGE:-"builder-aie-nv-cross"}

ARCHITECTURES=${ARCHITECTURES:-"amd64 arm64 s390x"}
