load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "checker.go",
        "checker-arm64.go",
    ],
    cgo = True,
    importpath = "kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/iommu-pci",
    visibility = ["//visibility:public"],
    deps = select({
        "@io_bazel_rules_go//go/platform:arm64": [
            "//staging/src/kubevirt.io/client-go/log:go_default_library",
            "//vendor/golang.org/x/sys/unix:go_default_library",
        ],
        "//conditions:default": [],
    }),
)
